app = "neoatende"

primary_region = "gru"

[build]
  dockerfile = "backend/Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false   # evita parar sozinho
  auto_start_machines = true   # sobe quando receber tráfego
  min_machines_running = 1     # garante pelo menos 1 ativa

  [[http_service.ports]]
    port = 80
    handlers = ["http"]

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 40
